services:
  dockerproxy:
    image: wollomatic/socket-proxy:1
    command:
      - '-loglevel=info'
      - '-allowfrom=dozzle' # allow only the small subnet "docker-proxynet"
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{2}/(containers/.*|events)|/_ping'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=300'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 65534:998 # change gid from 998 to the gid of the docker group on your host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet

  dozzle:
    image: amir20/dozzle:latest # make sure you use the most recent version
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    environment:
      DOZZLE_REMOTE_HOST: tcp://dockerproxy:2375
#     # add additional configuration here
#     # for example labels for traefik if needed
      # or expose the port to the host network:
#    ports:
#       - 127.0.0.1:8080:8080 # bind only to the host network
    networks:
      - docker-proxynet
      - dozzle

networks:
  docker-proxynet:
    internal: true
    attachable: false
  dozzle:
    driver: bridge
    attachable: false
